input_data_path: "data/heart_cleveland_upload.csv"
output_model_path: "models/model.pkl"
features_val_path: "data/features_val.csv"
target_val_path: "data/target_val.csv"
splitting_params:
  val_size: 0.2
  random_state: 3
preprocessing_params: 
  use_scaler: True
  use_custom_transformer: False
  scaler: "StandardScaler"
train_params:
  model_type: "RandomForestClassifier"
  random_state: 3
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "fbs"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  target_col: "condition"